version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: cimg/python:3.9.18

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "test_requirements.txt" }}

      - run:
          name: install
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r test_requirements.txt

      - run:
          name: run unit tests and generate coverage
          command: |
            . venv/bin/activate
            coverage run -m pytest -m unit -s onm/tests
            coverage xml

      - run:
          name: run integration tests
          command: |
            . venv/bin/activate
            pytest -m integration -s onm/tests --client_id $PLAID_CLIENT_ID --secret $PLAID_SECRET

      # - codecov/upload:
      #     file: coverage.xml
      #     token: $CODECOV_TOKEN

      - run:
          name: run linting via flake8
          command: |
            . venv/bin/activate
            flake8 onm

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "test_requirements.txt" }}
          paths:
            - "venv"

      - store_artifacts:
          path: test-reports
          destination: test-reports
