from typing import Dict

# https://plaid.com/blog/transactions-categorization-taxonomy/
# https://plaid.com/documents/transactions-personal-finance-category-taxonomy.csv
PLAID_PERSONAL_FINANCE_CATEGORIES = {
    "BANK_FEES": [
        "BANK_FEES_ATM_FEES",
        "BANK_FEES_FOREIGN_TRANSACTION_FEES",
        "BANK_FEES_INSUFFICIENT_FUNDS",
        "BANK_FEES_INTEREST_CHARGE",
        "BANK_FEES_OVERDRAFT_FEES",
        "BANK_FEES_OTHER_BANK_FEES",
    ],
    "ENTERTAINMENT": [
        "ENTERTAINMENT_CASINOS_AND_GAMBLING",
        "ENTERTAINMENT_MUSIC_AND_AUDIO",
        "ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS",
        "ENTERTAINMENT_TV_AND_MOVIES",
        "ENTERTAINMENT_VIDEO_GAMES",
        "ENTERTAINMENT_OTHER_ENTERTAINMENT",
    ],
    "FOOD_AND_DRINK": [
        "FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR",
        "FOOD_AND_DRINK_COFFEE",
        "FOOD_AND_DRINK_FAST_FOOD",
        "FOOD_AND_DRINK_GROCERIES",
        "FOOD_AND_DRINK_RESTAURANT",
        "FOOD_AND_DRINK_VENDING_MACHINES",
        "FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK",
    ],
    "GENERAL_MERCHANDISE": [
        "GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS",
        "GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES",
        "GENERAL_MERCHANDISE_CONVENIENCE_STORES",
        "GENERAL_MERCHANDISE_DEPARTMENT_STORES",
        "GENERAL_MERCHANDISE_DISCOUNT_STORES",
        "GENERAL_MERCHANDISE_ELECTRONICS",
        "GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES",
        "GENERAL_MERCHANDISE_OFFICE_SUPPLIES",
        "GENERAL_MERCHANDISE_ONLINE_MARKETPLACES",
        "GENERAL_MERCHANDISE_PET_SUPPLIES",
        "GENERAL_MERCHANDISE_SPORTING_GOODS",
        "GENERAL_MERCHANDISE_SUPERSTORES",
        "GENERAL_MERCHANDISE_TOBACCO_AND_VAPE",
        "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE",
    ],
    "GENERAL_SERVICES": [
        "GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING",
        "GENERAL_SERVICES_AUTOMOTIVE",
        "GENERAL_SERVICES_CHILDCARE",
        "GENERAL_SERVICES_CONSULTING_AND_LEGAL",
        "GENERAL_SERVICES_EDUCATION",
        "GENERAL_SERVICES_INSURANCE",
        "GENERAL_SERVICES_POSTAGE_AND_SHIPPING",
        "GENERAL_SERVICES_STORAGE",
        "GENERAL_SERVICES_OTHER_GENERAL_SERVICES",
    ],
    "GOVERNMENT_AND_NON_PROFIT": [
        "GOVERNMENT_AND_NON_PROFIT_DONATIONS",
        "GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES",
        "GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT",
        "GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT",
    ],
    "HOME_IMPROVEMENT": [
        "HOME_IMPROVEMENT_FURNITURE",
        "HOME_IMPROVEMENT_HARDWARE",
        "HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE",
        "HOME_IMPROVEMENT_SECURITY",
        "HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT",
    ],
    "INCOME": [
        "INCOME_DIVIDENDS",
        "INCOME_INTEREST_EARNED",
        "INCOME_RETIREMENT_PENSION",
        "INCOME_TAX_REFUND",
        "INCOME_UNEMPLOYMENT",
        "INCOME_WAGES",
        "INCOME_OTHER_INCOME",
    ],
    "LOAN_PAYMENTS": [
        "LOAN_PAYMENTS_CAR_PAYMENT",
        "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT",
        "LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT",
        "LOAN_PAYMENTS_MORTGAGE_PAYMENT",
        "LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT",
        "LOAN_PAYMENTS_OTHER_PAYMENT",
    ],
    "MEDICAL": [
        "MEDICAL_DENTAL_CARE",
        "MEDICAL_EYE_CARE",
        "MEDICAL_NURSING_CARE",
        "MEDICAL_PHARMACIES_AND_SUPPLEMENTS",
        "MEDICAL_PRIMARY_CARE",
        "MEDICAL_VETERINARY_SERVICES",
        "MEDICAL_OTHER_MEDICAL",
    ],
    "PERSONAL_CARE": [
        "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS",
        "PERSONAL_CARE_HAIR_AND_BEAUTY",
        "PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING",
        "PERSONAL_CARE_OTHER_PERSONAL_CARE",
    ],
    "RENT_AND_UTILITIES": [
        "RENT_AND_UTILITIES_GAS_AND_ELECTRICITY",
        "RENT_AND_UTILITIES_INTERNET_AND_CABLE",
        "RENT_AND_UTILITIES_RENT",
        "RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT",
        "RENT_AND_UTILITIES_TELEPHONE",
        "RENT_AND_UTILITIES_WATER",
        "RENT_AND_UTILITIES_OTHER_UTILITIES",
    ],
    "TRANSFER_IN": [
        "TRANSFER_IN_CASH_ADVANCES_AND_LOANS",
        "TRANSFER_IN_DEPOSIT",
        "TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS",
        "TRANSFER_IN_SAVINGS",
        "TRANSFER_IN_ACCOUNT_TRANSFER",
        "TRANSFER_IN_OTHER_TRANSFER_IN",
    ],
    "TRANSFER_OUT": [
        "TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS",
        "TRANSFER_OUT_SAVINGS",
        "TRANSFER_OUT_WITHDRAWAL",
        "TRANSFER_OUT_ACCOUNT_TRANSFER",
        "TRANSFER_OUT_OTHER_TRANSFER_OUT",
    ],
    "TRANSPORTATION": [
        "TRANSPORTATION_BIKES_AND_SCOOTERS",
        "TRANSPORTATION_GAS",
        "TRANSPORTATION_PARKING",
        "TRANSPORTATION_PUBLIC_TRANSIT",
        "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
        "TRANSPORTATION_TOLLS",
        "TRANSPORTATION_OTHER_TRANSPORTATION",
    ],
    "TRAVEL": [
        "TRAVEL_FLIGHTS",
        "TRAVEL_LODGING",
        "TRAVEL_RENTAL_CARS",
        "TRAVEL_OTHER_TRAVEL",
    ],
}

# The onm standard categories are a slight modification of Plaid categories
ONM_STANDARD_CATEGORIES = (
    [
        f"{p}:{c[len(p)+1:]}"
        for p, d in PLAID_PERSONAL_FINANCE_CATEGORIES.items()
        for c in d
    ]
    + list(PLAID_PERSONAL_FINANCE_CATEGORIES.keys())
    + ["UNKNOWN"]
)

# I found limited documentation of the Apple Card categories
APPLE_ONM_CATEGORY_MAPPING = {
    "Other": "UNKNOWN",
    "Transportation": "TRANSPORTATION",
    "Grocery": "FOOD_AND_DRINK:GROCERIES",
    "Entertainment": "ENTERTAINMENT",
    "Payment": "TRANSFER_IN:OTHER_TRANSFER_IN",
}

# The Amex categorization was listed on the "Year End Summary" page
# Kudos to ChatGPT for doing the majority of this mapping
AMEX_ONM_CATEGORY_MAPPING = {
    "Business Services": "GENERAL_SERVICES",
    "Business Services:Advertising": "GENERAL_SERVICES:OTHER_GENERAL_SERVICES",
    "Business Services:Banking": "GENERAL_SERVICES:ACCOUNTING_AND_FINANCIAL_PLANNING",
    "Business Services:Health Care": "MEDICAL:OTHER_MEDICAL",
    "Business Services:Insurance": "GENERAL_SERVICES:INSURANCE",
    "Communications": "RENT_AND_UTILITIES",
    "Communications:Cable & Internet": "RENT_AND_UTILITIES:INTERNET_AND_CABLE",
    "Communications:Mobile": "RENT_AND_UTILITIES:TELEPHONE",
    "Communications:Telephone": "RENT_AND_UTILITIES:TELEPHONE",
    "Entertainment": "ENTERTAINMENT",
    "Entertainment:Clubs": "ENTERTAINMENT:OTHER_ENTERTAINMENT",
    "Entertainment:Sports Events": "ENTERTAINMENT:SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS",  # noqa: E501
    "Entertainment:Theme Parks": "ENTERTAINMENT:SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS",  # noqa: E501
    "Entertainment:Theater": "ENTERTAINMENT:OTHER_ENTERTAINMENT",
    "Fees & Adjustments": "BANK_FEES",
    "Fees & Adjustments:Fees & Adjustments": "BANK_FEES",
    "Merchandise & Supplies": "GENERAL_MERCHANDISE",
    "Merchandise & Supplies:Appliances": "GENERAL_MERCHANDISE:ELECTRONICS",
    "Merchandise & Supplies:General Retail": "GENERAL_MERCHANDISE",
    "Merchandise & Supplies:Groceries": "FOOD_AND_DRINK:GROCERIES",
    "Merchandise & Supplies:Pharmacies": "MEDICAL:PHARMACIES_AND_SUPPLEMENTS",
    "Merchandise & Supplies:Mail Order": "GENERAL_MERCHANDISE:ONLINE_MARKETPLACES",
    "Other": "UNKNOWN",
    "Other:Charities": "GOVERNMENT_AND_NON_PROFIT:DONATIONS",
    "Other:Education": "GENERAL_SERVICES:EDUCATION",
    "Other:Government Svcs": "GENERAL_SERVICES",
    "Other:Utilities": "RENT_AND_UTILITIES:GAS_AND_ELECTRICITY",
    "Other:Miscellaneous": "GENERAL_SERVICES:OTHER_GENERAL_SERVICES",
    "Restaurant": "FOOD_AND_DRINK",
    "Restaurant:Bar & Café": "FOOD_AND_DRINK:BEER_WINE_AND_LIQUOR",
    "Restaurant:Restaurant": "FOOD_AND_DRINK:RESTAURANT",
    "Transportation": "TRANSPORTATION",
    "Transportation:Air Services": "TRAVEL:FLIGHTS",
    "Transportation:Boat Services": "TRANSPORTATION:OTHER_TRANSPORTATION",
    "Transportation:Rail Services": "TRANSPORTATION:PUBLIC_TRANSIT",
    "Transportation:Fuel": "TRANSPORTATION:GAS",
    "Transportation:Parking Charges": "TRANSPORTATION:PARKING",
    "Transportation:Tolls & Fees": "TRANSPORTATION:TOLLS",
    "Travel": "TRAVEL",
    "Travel:Airline": "TRAVEL:FLIGHTS",
    "Travel:Lodging": "TRAVEL:LODGING",
    "Travel:Travel Agencies": "TRAVEL:OTHER_TRAVEL",
    "Travel:Vehicle Rental": "TRAVEL:RENTAL_CARS",
}

# https://mint.intuit.com/mint-categories
# Kudos to ChatGPT for doing the majority of this mapping
MINT_ONM_CATEGORY_MAPPING = {
    "Income": "INCOME",
    "Income:Paycheck": "INCOME:WAGES",
    "Income:Investment": "TRANSFER_IN:INVESTMENT_AND_RETIREMENT_FUNDS",
    "Income:Returned Purchase": "TRANSFER_IN:OTHER_TRANSFER_IN",
    "Income:Bonus": "INCOME:OTHER_INCOME",
    "Income:Interest Income": "INCOME:INTEREST_EARNED",
    "Income:Reimbursement": "TRANSFER_IN:OTHER_TRANSFER_IN",
    "Income:Rental Income": "TRANSFER_IN:OTHER_TRANSFER_IN",
    "Miscellaneous": "TRANSFER_IN",
    "Miscellaneous:Cash & ATM": "TRANSFER_IN:CASH_ADVANCES_AND_LOANS",
    "Miscellaneous:Check": "TRANSFER_IN:DEPOSIT",
    "Entertainment": "ENTERTAINMENT",
    "Entertainment:Arts": "ENTERTAINMENT:OTHER_ENTERTAINMENT",
    "Entertainment:Music": "ENTERTAINMENT:MUSIC_AND_AUDIO",
    "Entertainment:Movies & DVDs": "ENTERTAINMENT:TV_AND_MOVIES",
    "Entertainment:Newspaper & Magazines": "ENTERTAINMENT:OTHER_ENTERTAINMENT",
    "Entertainment:Amusement": "ENTERTAINMENT:SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS",  # noqa: E501
    "Education": "GENERAL_SERVICES:EDUCATION",
    "Education:Tuition": "GENERAL_SERVICES:EDUCATION",
    "Education:Student Loan": "LOAN_PAYMENTS:STUDENT_LOAN_PAYMENT",
    "Education:Books & Supplies": "GENERAL_SERVICES:EDUCATION",
    "Shopping": "GENERAL_MERCHANDISE",
    "Shopping:Clothing": "GENERAL_MERCHANDISE:CLOTHING_AND_ACCESSORIES",
    "Shopping:Books": "GENERAL_MERCHANDISE:BOOKSTORES_AND_NEWSSTANDS",
    "Shopping:Electronics & Software": "GENERAL_MERCHANDISE:ELECTRONICS",
    "Shopping:Hobbies": "GENERAL_MERCHANDISE",
    "Shopping:Sporting Goods": "GENERAL_MERCHANDISE:SPORTING_GOODS",
    "Personal Care": "PERSONAL_CARE",
    "Personal Care:Laundry": "PERSONAL_CARE:LAUNDRY_AND_DRY_CLEANING",
    "Personal Care:Hair": "PERSONAL_CARE:HAIR_AND_BEAUTY",
    "Personal Care:Spa & Massage": "PERSONAL_CARE:OTHER_PERSONAL_CARE",
    "Health & Fitness": "MEDICAL",
    "Health & Fitness:Dentist": "MEDICAL:DENTAL_CARE",
    "Health & Fitness:Doctor": "MEDICAL:PRIMARY_CARE",
    "Health & Fitness:Eye Care": "MEDICAL:EYE_CARE",
    "Health & Fitness:Pharmacy": "MEDICAL:PHARMACIES_AND_SUPPLEMENTS",
    "Health & Fitness:Health Insurance": "GENERAL_SERVICES:INSURANCE",
    "Health & Fitness:Gym": "PERSONAL_CARE:GYMS_AND_FITNESS_CENTERS",
    "Health & Fitness:Sports": "GENERAL_MERCHANDISE:SPORTING_GOODS",
    "Kids": "GENERAL_SERVICES:CHILDCARE",
    "Kids:Kids Activities": "ENTERTAINMENT",
    "Kids:Allowance": "INCOME:OTHER_INCOME",
    "Kids:Baby Supplies": "GENERAL_MERCHANDISE:OTHER_GENERAL_MERCHANDISE",
    "Kids:Babysitter & Daycare": "GENERAL_SERVICES:CHILDCARE",
    "Kids:Child Support": "GENERAL_SERVICES:CHILDCARE",
    "Kids:Toys": "GENERAL_MERCHANDISE:GIFTS_AND_NOVELTIES",
    "Food & Dining": "FOOD_AND_DRINK",
    "Food & Dining:Groceries": "FOOD_AND_DRINK:GROCERIES",
    "Food & Dining:Coffee Shops": "FOOD_AND_DRINK:COFFEE",
    "Food & Dining:Fast Food": "FOOD_AND_DRINK:FAST_FOOD",
    "Food & Dining:Restaurants": "FOOD_AND_DRINK:RESTAURANT",
    "Food & Dining:Alcohol & Bars": "FOOD_AND_DRINK:BEER_WINE_AND_LIQUOR",
    "Food & Dining:Food Delivery": "FOOD_AND_DRINK:OTHER_FOOD_AND_DRINK",
    "Gifts & Donations": "GENERAL_MERCHANDISE:GIFTS_AND_NOVELTIES",
    "Gifts & Donations:Gift": "GENERAL_MERCHANDISE:GIFTS_AND_NOVELTIES",
    "Gifts & Donations:Charity": "GOVERNMENT_AND_NON_PROFIT:DONATIONS",
    "Investments": "TRANSFER_OUT:INVESTMENT_AND_RETIREMENT_FUNDS",
    "Investments:Deposit": "TRANSFER_IN:DEPOSIT",
    "Investments:Withdrawal": "TRANSFER_OUT:WITHDRAWAL",
    "Investments:Dividend & Cap Gains": "INCOME:DIVIDENDS",
    "Investments:Buy": "TRANSFER_OUT:INVESTMENT_AND_RETIREMENT_FUNDS",
    "Investments:Sell": "TRANSFER_IN:INVESTMENT_AND_RETIREMENT_FUNDS",
    "Bills & Utilities": "RENT_AND_UTILITIES",
    "Bills & Utilities:Television": "RENT_AND_UTILITIES:INTERNET_AND_CABLE",
    "Bills & Utilities:Home Phone": "RENT_AND_UTILITIES:TELEPHONE",
    "Bills & Utilities:Internet": "RENT_AND_UTILITIES:INTERNET_AND_CABLE",
    "Bills & Utilities:Mobile Phone": "RENT_AND_UTILITIES:TELEPHONE",
    "Bills & Utilities:Utilities": "RENT_AND_UTILITIES:OTHER_UTILITIES",
    "Auto & Transport": "TRANSPORTATION",
    "Auto & Transport:Gas & Fuel": "TRANSPORTATION:GAS",
    "Auto & Transport:Parking": "TRANSPORTATION:PARKING",
    "Auto & Transport:Service & Parts": "TRANSPORTATION:OTHER_TRANSPORTATION",
    "Auto & Transport:Auto Payment": "LOAN_PAYMENTS:CAR_PAYMENT",
    "Auto & Transport:Auto Insurance": "GENERAL_SERVICES:INSURANCE",
    "Auto & Transport:Ride Share": "TRANSPORTATION:TAXIS_AND_RIDE_SHARES",
    "Auto & Transport:Public Transportation": "TRANSPORTATION:PUBLIC_TRANSIT",
    "Travel": "TRAVEL",
    "Travel:Air Travel": "TRAVEL:FLIGHTS",
    "Travel:Hotel": "TRAVEL:LODGING",
    "Travel:Rental Car & Taxi": "TRAVEL:RENTAL_CARS",
    "Travel:Vacation": "TRAVEL:OTHER_TRAVEL",
    "Fees & Charges": "BANK_FEES",
    "Fees & Charges:Service Fee": "GENERAL_SERVICES:OTHER_GENERAL_SERVICES",
    "Fees & Charges:Late Fee": "BANK_FEES:OTHER_BANK_FEES",
    "Fees & Charges:Finance Charge": "BANK_FEES:OTHER_BANK_FEES",
    "Fees & Charges:ATM Fee": "BANK_FEES:ATM_FEES",
    "Fees & Charges:Bank Fee": "BANK_FEES:OTHER_BANK_FEES",
    "Fees & Charges:Trade Commissions": "BANK_FEES:OTHER_BANK_FEES",
    "Fees & Charges:Loan Principal": "LOAN_PAYMENTS:OTHER_PAYMENT",
    "Business Services": "GENERAL_SERVICES",
    "Business Services:Advertising": "GENERAL_SERVICES:OTHER_GENERAL_SERVICES",
    "Business Services:Office Supplies": "GENERAL_MERCHANDISE:OFFICE_SUPPLIES",
    "Business Services:Printing": "GENERAL_SERVICES:OTHER_GENERAL_SERVICES",
    "Business Services:Shipping": "GENERAL_SERVICES:POSTAGE_AND_SHIPPING",
    "Business Services:Legal": "GENERAL_SERVICES:CONSULTING_AND_LEGAL",
    "Taxes": "GOVERNMENT_AND_NON_PROFIT:TAX_PAYMENT",
    "Taxes:Federal Tax": "GOVERNMENT_AND_NON_PROFIT:TAX_PAYMENT",
    "Taxes:State Tax": "GOVERNMENT_AND_NON_PROFIT:TAX_PAYMENT",
    "Taxes:Local Tax": "GOVERNMENT_AND_NON_PROFIT:TAX_PAYMENT",
    "Taxes:Sales Tax": "GOVERNMENT_AND_NON_PROFIT:TAX_PAYMENT",
    "Home": "HOME_IMPROVEMENT",
    "Home:Home Supplies": "GENERAL_MERCHANDISE:CONVENIENCE_STORES",
    "Home:Home Supplies": "GENERAL_MERCHANDISE:CONVENIENCE_STORES",
    "Home:Home Improvement": "HOME_IMPROVEMENT:OTHER_HOME_IMPROVEMENT",
    "Home:Home Insurance": "GENERAL_SERVICES:INSURANCE",
    "Home:Home Services": "GENERAL_SERVICES:OTHER_GENERAL_SERVICES",
    "Home:Mortgage & Rent": "RENT_AND_UTILITIES:RENT",
    "Home:Furnishings": "HOME_IMPROVEMENT:FURNITURE",
}


def get_onm_category(
    primary: str, detailed: str = None, mapping: Dict[str, str] = None
) -> str:
    if detailed is not None:
        category = f"{primary}:{detailed}"
        if category in mapping:
            return mapping[category]
    return mapping.get(primary, "UNKNOWN")
